import { Project } from "./types";

export const PROJECTS: Project[] = [
  // ────────────────────────────────────────────────────────────────
  // FEATURED
  // ────────────────────────────────────────────────────────────────
  {
    slug: "sidlak-ii",
    title: "SIDLAK II",
    type: "Autonomous Electric Vehicle",
    categories: ["prototype-vehicle", "fabrication", "simulation-analysis"],
    featured: true,
    sourceVerified: true,
    summary:
      "A ground-up vehicle development program completed in under five months, combining mechanical design, autonomous-system integration, rapid prototyping, and logistics optimization under tight resource and time constraints.",
    tags: [
      "Vehicle Design",
      "Mechanical Design",
      "Autonomous Systems",
      "CAD",
      "DFMA",
      "Design Optimization",
      "Rapid Prototyping",
      "Fabrication",
      "Steering System",
      "Electric Vehicle",
      "Modular Design",
      "Design for Manufacturing",
      "Shell Eco-marathon",
    ],
    hero: {
      file: "hero.jpg",
      alt: "SIDLAK II autonomous electric vehicle rendered in white and burnt-orange livery",
      caption: "SIDLAK II vehicle",
    },
    analysisImage: { file: "fea-roll-bar.jpg", alt: "Roll bar static FEA stress plot", caption: "Roll bar FEA" },
    problem: [
      "Develop an autonomous electric vehicle from scratch with less than five months of preparation before international competition.",
      "Design the vehicle around strict technical, dimensional, weight, manufacturing, and transportation constraints while working with limited fabrication resources.",
      "Integrate the mechanical platform with the autonomous driving system without compromising reliability, serviceability, or transportability.",
      "Prepare the vehicle for international technical inspection and competition within a highly compressed development and testing timeline.",
    ],
    role: {
      title: "Mechanical Lead / Vehicle Designer",
      points: [
        "Led the mechanical development of the entire vehicle, from architecture and packaging through detailed CAD and fabrication.",
        "Designed the chassis, wheel assemblies, motor mounts, steering system, structural components, and mechanical interfaces.",
        "Developed the autonomous steering rack-and-pinion system and integrated its mechanical components with the autonomous control architecture.",
        "Designed the vehicle around available manufacturing capabilities, including hand fabrication and 3D-printed components.",
        "Coordinated mechanical integration with electrical, autonomous, and other vehicle subsystems.",
        "Re-engineered the vehicle into a modular architecture to significantly reduce transportation and freight requirements.",
        "Supported fabrication, assembly, testing, troubleshooting, and preparation for technical inspection.",
      ],
    },
    results: [
      "Ground-up vehicle development in under five months — took the vehicle from concept and system architecture through CAD, fabrication, mechanical integration, testing, and international technical inspection under a highly compressed timeline.",
      "57.7% freight-volume reduction through metric-driven modular design — dimensional interfaces and modular assemblies built around actual component measurements, optimizing packed volume, assembly/disassembly time, and transport efficiency.",
      "Hybrid body-cover fabrication for rapid development — combined fiberglass molding, a 3D-printed windshield, and optimized 3D-printing strategies for the aerodynamic body with minimal tooling.",
      "Rapid autonomous-steering integration — the fastest practical fabrication route for an autonomous steering system, sizing the actuator around a measured 6.38 N·m minimum static torque and 12.8 N·m design requirement, using a NEMA 34 stepper with a 2:1 reduction.",
      "Engineering-validated vehicle architecture — chassis, steering, wheel-mounting, and structural systems developed and validated through CAD, engineering calculations, FEA, and kinematic analysis, achieving a 6.24 m turning radius against the competition maneuverability requirement.",
      "Designed for fabrication, assembly, and repair — modularized critical structures with standardized interfaces, including a removable bolted front sub-structure, so components can be independently assembled, transported, and serviced.",
      "8th Overall internationally — successfully deployed the completed vehicle at the Shell Eco-marathon Autonomous Driving Competition in Poland after an accelerated ground-up development program.",
    ],
    approach: {
      flow: "Constraint → Measure → Optimize → Fabricate → Integrate → Validate",
      body: "Every major design decision was approached around one question: what is the fastest, most manufacturable, and most resource-efficient way to achieve the required engineering performance? That drove a modular vehicle architecture, hybrid fabrication methods, dimension-driven packaging, and rapid autonomous-system integration rather than a conventional development workflow.",
    },
    sections: [
      {
        heading: "Structural Validation — Roll Bar FEA",
        body: [
          "Static FEA was performed under the required 800 N loading condition. The roll bar experienced a maximum stress of 0.0267 MPa, well below the 262 MPa yield strength of galvanized steel, confirming structural integrity with a high safety margin.",
        ],
      },
      {
        heading: "Structural Validation — Flanged Connection FEA",
        body: [
          "The bolted flange joint connecting the front sub-structure to the main chassis, together with the surrounding roll-cage gussets, was validated using finite element analysis under a static load case representative of frontal impact and braking loads. The design target was a minimum load capacity of 1200 N at the flange interface, consistent with the competition's structural safety-margin expectations for a bolted, non-welded connection.",
        ],
      },
    ],
    gallery: [
      { file: "chassis-subassembly.jpg", alt: "Chassis and subassembly CAD model", caption: "Chassis subassembly" },
      { file: "body-fab-mold-2.jpg", alt: "Molded body shell section", caption: "Molded body shell" },
      { file: "modular-frame-1.jpg", alt: "Modular chassis component", caption: "Flanged connection" },
      { file: "modular-frame-2.jpg", alt: "Modular chassis CAD render", caption: "Modular crating assembly" },
      { file: "competition-poland.jpg", alt: "Team at the Shell Eco-marathon Autonomous Driving Competition in Poland", caption: "Contest photo in Poland" },
      { file: "fea-roll-bar.jpg", alt: "Roll bar static FEA stress plot", caption: "Roll bar FEA" },
      { file: "fea-flange.jpg", alt: "Flanged connection FEA stress plot", caption: "Flanged connection FEA" },
    ],
  },
  {
    slug: "aem-vtmd",
    title: "AEM-VTMD",
    type: "Autonomous Electromagnetic Variable Tuned Mass Damper",
    categories: ["simulation-analysis", "products"],
    featured: true,
    sourceVerified: true,
    summary:
      "An undergraduate research project developing an Autonomous Electromagnetic Variable Tuned Mass Damper for adaptive vibration control and energy harvesting — combining variable mechanical stiffness, electromagnetic damping, real-time sensing, and energy conversion to dynamically respond to changing vibration conditions.",
    tags: [
      "Undergraduate Research",
      "Mechanical Design",
      "Vibration Control",
      "Tuned Mass Damper",
      "Energy Harvesting",
      "Mechatronics",
      "MATLAB",
      "CAD",
      "Dynamic Analysis",
      "Design Optimization",
    ],
    hero: { file: "hero.jpg", alt: "AEM-VTMD mechanical assembly rendered in matte black", caption: "AEM-VTMD assembly" },
    analysisImage: { file: "matlab-frequency-response.jpg", alt: "MATLAB 2-DOF ode45 frequency-response simulation", caption: "Frequency response analysis" },
    problem: [
      "Develop an adaptive vibration-control system capable of responding to changing excitation conditions while also recovering energy from structural motion.",
      "Conventional tuned mass dampers are typically designed around a fixed operating condition, limiting their effectiveness when the excitation frequency changes.",
      "Develop a variable tuned mass damper capable of adjusting its effective stiffness to respond to changing vibration conditions.",
      "Integrate electromagnetic damping and energy harvesting without compromising the mechanical vibration-control function.",
      "Develop the system as a compact, self-calibrating platform suitable for real-time sensing, adjustment, and monitoring.",
    ],
    role: {
      title: "Mechanical Designer — Undergraduate Research",
      points: [
        "Designed the mechanical architecture of the AEM-VTMD as part of the undergraduate research project.",
        "Developed the variable-stiffness mechanism used to adjust the system's dynamic response.",
        "Designed the electromagnetic damping and energy-harvesting mechanical assembly.",
        "Worked on the arrangement of the magnet array, conductive plate, springs, coils, and supporting structure.",
        "Performed mechanical sizing, CAD development, and design iteration.",
        "Supported integration of sensors and control hardware with the project's monitoring dashboard.",
        "Used MATLAB-based analysis to evaluate vibration response and guide the mechanical design.",
      ],
    },
    results: [
      "Variable-stiffness vibration control — a mechanically adjustable spring architecture that lets the TMD's effective stiffness be modified in response to changing excitation conditions.",
      "Integrated electromagnetic damping and energy harvesting — combined the vibration-control mechanism with an electromagnetic system that generates damping through eddy-current effects while recovering electrical energy from relative motion.",
      "514.35 N·s/m damping coefficient — achieved with the final magnet / conductive-plate configuration and a 1 mm air gap.",
      "77.6% simulated vibration reduction — reduced the evaluated displacement response from 0.2813 mm to 0.0629 mm through the tuned mass damper system.",
      "Adaptive frequency response — demonstrated how changing mechanical stiffness shifts the system response, providing a basis for autonomous tuning across varying vibration conditions.",
      "Integrated sensing and monitoring — connected the mechanical system with vibration sensors, control electronics, and a monitoring dashboard for real-time adjustment and evaluation.",
    ],
    approach: {
      flow: "Model → Design → Simulate → Fabricate → Sense → Adjust → Validate",
      body: "The research followed an iterative mechanical-design approach in which the TMD's mass, stiffness, damping, magnetic configuration, and mechanical interfaces were developed together. Simulation and experimental feedback were used to refine the design toward an adaptive system capable of both vibration suppression and energy conversion.",
    },
    gallery: [
      {
        file: "halbach-magnet-damping.jpg",
        alt: "N52 Halbach magnet array over a conductive damping plate",
        caption: "Halbach magnet + conductive plate damping",
      },
      { file: "assembly.jpg", alt: "AEM-VTMD housing assembly, exploded components", caption: "Exploded assembly" },
      { file: "electronics-architecture.jpg", alt: "Sensing and control electronics architecture diagram", caption: "Electronics schematic" },
      { file: "matlab-frequency-response.jpg", alt: "MATLAB 2-DOF ode45 frequency-response simulation", caption: "Frequency response analysis" },
      { file: "dashboard.jpg", alt: "Real-time monitoring dashboard", caption: "Monitoring dashboard" },
    ],
  },
  {
    slug: "body-misting",
    title: "Automated Body Misting Device",
    type: "Fluid System & Product Development",
    categories: ["products", "fabrication", "simulation-analysis"],
    featured: true,
    sourceVerified: true,
    summary:
      "An automated body-misting system delivering a 60:40 water-oil mixture, developed across three physical prototypes over roughly three months while optimizing the fluid path, passive mixing system, tubing, and mechanical assembly.",
    tags: [
      "Product Development",
      "Mechanical Design",
      "Fluid Systems",
      "Prototyping",
      "Solid Edge",
      "Design Optimization",
      "DFMA",
    ],
    hero: { file: "hero.jpg", alt: "Assembled misting device housing in black and white", caption: "Misting device assembly" },
    analysisImage: { file: "pressure-simulation.jpg", alt: "Pressure-loss simulation across three mixing-tube designs", caption: "Pressure-loss simulation (CFD)" },
    problem: [
      "Develop a compact misting system capable of reliably delivering a 60:40 water-oil mixture.",
      "Develop the mechanical system for simultaneously handling and mixing two fluids.",
      "Achieve consistent misting without relying on an emulsifier.",
      "Manage pressure losses through the pump, tubing, mixing, and spray system.",
      "Develop a functional prototype within a highly compressed product-development cycle.",
    ],
    role: {
      title: "Mechanical Designer / Product Development",
      points: [
        "Designed the complete mechanical assembly in Solid Edge.",
        "Developed the high-pressure tubing system around a 12 V diaphragm pump.",
        "Designed and integrated a passive mixing tube for water-oil mixing.",
        "Developed and evaluated three physical prototype iterations over approximately three months.",
        "Investigated fluid-flow behavior and mechanical causes of performance issues.",
        "Modified components based on prototype testing and observed failure modes.",
        "Worked across mechanical, fluid, and product-integration requirements.",
      ],
    },
    results: [
      "50% reduction in total pump-system pressure loss through fluid-path redesign.",
      "95% misting success rate for the targeted 60:40 water-oil ratio.",
      "Three prototype iterations in ~3 months — used rapid physical iteration rather than relying solely on simulation.",
      "Passive mixing system — achieved water-oil mixing without the use of an emulsifier.",
      "Integrated pump, tubing, mixing, and atomization into a compact product architecture.",
    ],
    approach: {
      flow: "Prototype → Test → Identify Losses → Redesign → Rebuild → Validate",
      body: "The development focused on rapid physical iteration, using each prototype to identify fluid-flow and mechanical limitations before refining the next version.",
    },
    sections: [
      {
        heading: "Passive Mixing & Pressure-Loss Analysis",
        body: [
          "Design 1's sharp internal edges induced a high pressure drop from strong flow separation and turbulence.",
          "Design 2's streamlined profile minimized pressure drop by reducing flow resistance.",
          "Design 3 landed in between, with a moderate pressure drop — informing the final tube geometry.",
        ],
      },
    ],
    gallery: [
      { file: "misting-nozzle.jpg", alt: "Close-up of the misting nozzle assembly", caption: "Misting nozzle" },
      { file: "wall-hook.jpg", alt: "Wall-hook mounting detail on the housing", caption: "Wall-hook mount" },
      { file: "prototype-v1-v3.jpg", alt: "Prototype versions 1 through 3, side by side", caption: "Prototype V1 to V3" },
      { file: "pressure-simulation.jpg", alt: "Pressure-loss simulation across three mixing-tube designs", caption: "Pressure-loss simulation" },
      { file: "backplate.jpg", alt: "Custom aluminum backplate", caption: "Aluminum backplate" },
    ],
  },
  {
    slug: "key-fob-holder",
    title: "Key Fob Holder",
    type: "Miniature Mechanism Development",
    categories: ["products", "fabrication"],
    featured: true,
    sourceVerified: true,
    summary:
      "A miniature mechanical mechanism developed for a luxury vehicle keyfob display, involving the design and evaluation of multiple clamping and latching architectures within a highly constrained package.",
    tags: [
      "Mechanism Design",
      "Kinematics",
      "Miniature Mechanisms",
      "Parametric CAD",
      "Tolerance Design",
      "Spring Mechanisms",
      "Solid Edge",
    ],
    hero: { file: "hero.jpg", alt: "Key fob display tray with three cardioid-mechanism holders", caption: "Key fob display tray" },
    problem: [
      "Create a compact mechanism capable of securely holding a luxury vehicle keyfob while fitting inside a highly constrained miniature package.",
      "Develop a retractable clamping mechanism for varying keyfob sizes.",
      "Maintain reliable clamping while minimizing mechanism size.",
      "Solve the interaction between springs, clamps, latches, and the rotating display mechanism.",
      "Achieve reliable operation despite extremely small component features and clearances.",
    ],
    role: {
      title: "Mechanical Mechanism Designer",
      points: [
        "Designed and evaluated multiple miniature clamping and latching concepts.",
        "Developed rack-and-pinion, push-latch, toggle-clamp, and cardioid mechanisms.",
        "Designed spring-loaded components and investigated their kinematics.",
        "Worked on miniature tolerances and fabrication constraints.",
        "Redesigned components based on physical/mechanical limitations.",
        "Developed the final cardioid mechanism and supporting shaft guide.",
        "Optimized component thicknesses, slots, clearances, and interfaces.",
      ],
    },
    results: [
      "Multiple mechanism architectures evaluated rather than committing to the first concept.",
      "Cardioid latch concept developed as an alternative compact latching mechanism.",
      "5 mm mechanism travel accommodated within the cardioid profile.",
      "Miniature tolerance optimization — modified slot geometry, component thickness, and guide features to address travel and structural issues.",
      "Developed a spring-loaded clamping architecture capable of accommodating varying keyfob sizes.",
    ],
    approach: {
      flow: "Concept → Kinematics → Prototype → Failure Mode → Redesign → Miniaturize",
      body: "The mechanism was developed through iterative mechanism comparison, prioritizing reliability, packaging, actuation, and manufacturability at miniature scale.",
    },
    gallery: [
      { file: "mechanism-detail-1.jpg", alt: "Cardioid mechanism, section view with retracted clamp", caption: "Cardioid mechanism section" },
      { file: "mechanism-detail-2.jpg", alt: "Three-slot cardioid mechanism array, underside view", caption: "Cardioid array underside" },
    ],
  },
  {
    slug: "beetleweight-battle-bot",
    title: "Beetleweight Battle Bot",
    type: "Combat Robotics & Mechanical Optimization",
    categories: ["products", "fabrication"],
    featured: true,
    sourceVerified: true,
    summary:
      "A compact combat-robot design developed around strict weight and packaging constraints, balancing drivetrain performance, traction, weapon performance, and structural requirements within a limited mass envelope.",
    tags: [
      "Combat Robotics",
      "Mechanical Design",
      "BLDC",
      "Drivetrain Design",
      "Weight Optimization",
      "Weapon Design",
      "CAD",
      "Robotics",
    ],
    hero: { file: "hero.jpg", alt: "Beetleweight combat robot, full assembly with red accents", caption: "Full assembly" },
    problem: [
      "Maximize combat performance within an extremely constrained mass and package envelope.",
      "Design a compact combat robot around the strict Beetleweight weight constraint.",
      "Balance drivetrain torque, traction, weapon performance, structural strength, and overall mass.",
      "Package high-performance components into a compact mechanical architecture.",
      "Ensure the system can survive aggressive dynamic loading while remaining serviceable.",
    ],
    role: {
      title: "Mechanical Designer",
      points: [
        "Developed the mechanical architecture of the combat robot.",
        "Designed the drivetrain and wheel arrangement.",
        "Integrated BLDC motors into the propulsion system.",
        "Developed the silicon-padded wheel concept for increased traction.",
        "Designed the T7 aluminum weapon and its mechanical integration.",
        "Optimized component placement and packaging around the weight constraint.",
      ],
    },
    results: [
      "Weight-driven mechanical optimization — every major component was evaluated in terms of performance-per-gram.",
      "BLDC drivetrain — selected high-power electric propulsion within the compact vehicle envelope.",
      "High-traction wheel system — integrated silicon-padded wheels to improve contact and traction.",
      "T7 aluminum weapon — balanced weapon mass, strength, and packaging.",
      "Compact system architecture — integrated propulsion, weapon, structure, and supporting mechanisms into a constrained footprint.",
    ],
    approach: {
      flow: "Mass Budget → Performance Requirement → Component Selection → Packaging → Structural Optimization → Build",
      body: "The design treated weight as a system-level engineering resource, balancing torque, traction, weapon performance, structural integrity, and manufacturability rather than optimizing each subsystem independently.",
    },
    gallery: [
      { file: "assembly-2.jpg", alt: "Combat robot assembly, drivetrain and weapon detail", caption: "Drivetrain and weapon detail" },
      { file: "carbon-fiber-housing.jpg", alt: "Carbon fiber housing component", caption: "Carbon fiber housing" },
      { file: "weapon-render.jpg", alt: "T7 aluminum weapon disc, rendered", caption: "T7 weapon disc" },
      { file: "weapon-drawing.jpg", alt: "Aluminum T7 weapon engineering drawing", caption: "Weapon engineering drawing" },
    ],
  },
  {
    slug: "mood-coaster",
    title: "Mood Coaster",
    type: "Compact Mechanism & Cable Routing",
    categories: ["products", "fabrication"],
    featured: true,
    sourceVerified: true,
    summary:
      "A compact mechanical design project exploring folding-hinge architectures for a mood-tracking coaster, with emphasis on cable routing, stiffness, mechanism complexity, and user actuation.",
    tags: ["Mechanism Design", "Cable Routing", "Hinge Design", "DFMA", "CAD", "Design Optimization"],
    hero: { file: "hero.jpg", alt: "Mood Coaster, open clamshell showing lens and floral-patterned lid", caption: "Mood Coaster, open" },
    problem: [
      "Create a compact folding mechanical interface while maintaining reliable cable routing and user operation.",
      "Package the mechanical and flex-cable system into a compact coaster.",
      "Allow the top portion to open and close repeatedly.",
      "Prevent the flex cable from interfering with the hinge.",
      "Balance stiffness, cable protection, mechanism complexity, and user force.",
    ],
    role: {
      title: "Mechanical Designer / Mechanism Optimization",
      points: [
        "Developed three hinge architectures.",
        "Designed the mechanical body and hinge interfaces.",
        "Evaluated flex-cable routing through the hinge.",
        "Developed a hinge alternative.",
        "Compared stiffness, cable exposure, complexity, and opening force.",
      ],
    },
    results: [
      "Three hinge concepts evaluated.",
      "Three-hinge design identified as the safer/more viable architecture because the flex cable only needs to pass through the central hinge.",
      "Torque-hinge concept increased stiffness, but also increased opening/closing force.",
      "Developed multiple cable-routing strategies within a constrained hinge architecture.",
    ],
    approach: {
      flow: "Package → Route → Hinge → Compare → Optimize → Select",
      body: "The mechanism was developed by comparing hinge architectures against the same constraints — cable exposure, stiffness, complexity, and the force needed to open and close the unit — rather than committing to the first working hinge.",
    },
    gallery: [
      { file: "closed-lid.jpg", alt: "Mood Coaster, closed, floral-patterned lid", caption: "Closed lid" },
      { file: "open-screen.jpg", alt: "Mood Coaster, open, showing mood-check screen with emoji options", caption: "Mood-check screen" },
      { file: "hinge-detail.jpg", alt: "Mood Coaster hinge mechanism, open at an angle", caption: "Hinge mechanism" },
    ],
  },
  {
    slug: "aerosol-dispenser",
    title: "Aerosol Insecticide Dispenser",
    type: "Spray Mechanism Redesign & Root-Cause Analysis",
    categories: ["products"],
    featured: true,
    sourceVerified: true,
    summary:
      "A mechanical redesign project focused on improving the reliability of an automated aerosol insecticide dispenser by identifying and resolving mechanical issues in the spray-cap and nozzle system.",
    tags: [
      "Mechanical Design",
      "Root-Cause Analysis",
      "Product Redesign",
      "Solid Edge",
      "Spray Systems",
      "Prototyping",
      "Design Optimization",
    ],
    hero: { file: "hero.jpg", alt: "Wall-mounted aerosol insecticide dispenser with digital display", caption: "Wall-mounted dispenser" },
    problem: [
      "Resolve mechanical reliability issues in an automated pest-control spraying mechanism.",
      "Improve the reliability of the spray mechanism.",
      "Resolve inconsistent flow and clogging.",
      "Address leakage around the spray cap.",
      "Improve the existing design without completely redesigning the product.",
    ],
    role: {
      title: "Mechanical Design / Root-Cause Analysis",
      points: [
        "Investigated mechanical failures in the spray-cap system.",
        "Performed root-cause analysis.",
        "Redesigned the spray-cap/nozzle geometry.",
        "Iterated the design in Solid Edge.",
        "Evaluated the redesigned mechanism against the previous configuration.",
      ],
    },
    results: [
      "90% improvement in spray success rate through mechanical redesign.",
      "83% reduction in leakage compared with the previous design.",
      "Improved consistency of flow and reduced clogging.",
    ],
    approach: {
      flow: "Failure → Root Cause → Redesign → Prototype → Test → Verify",
      body: "Rather than redesigning the dispenser from scratch, the project traced spray failures back to their mechanical root cause in the cap/nozzle interface, then validated a targeted redesign against the original configuration.",
    },
    gallery: [
      { file: "wall-unit.jpg", alt: "Assembled wall-mounted dispenser with digital display", caption: "Wall unit" },
      { file: "spray-cap-section.jpg", alt: "Section view of the redesigned spray cap", caption: "Spray cap section view" },
      { file: "front-view.jpg", alt: "Dispenser front view", caption: "Front view" },
      { file: "nozzle-housing.jpg", alt: "Nozzle housing, rendered", caption: "Nozzle housing" },
    ],
  },
  {
    slug: "thread-finder",
    title: "Thread Finder",
    type: "Mechanical Sensing & Test Rig Development",
    categories: ["products", "fabrication"],
    featured: true,
    sourceVerified: true,
    summary:
      "A mechanical concept-development project for automated bolt and nut thread identification, focusing on repeatable positioning, sensor geometry, gripping mechanisms, and tolerance-driven design decisions.",
    tags: [
      "Mechanism Design",
      "Tolerance Analysis",
      "Sensor Integration",
      "Test Rig Design",
      "Design Validation",
      "CAD",
      "Precision Engineering",
    ],
    hero: { file: "hero.jpg", alt: "Thread finder test rig housing", caption: "Thread finder housing" },
    problem: [
      "Develop a mechanical concept capable of reliably identifying bolt and nut thread profiles across different sizes.",
      "Develop a mechanism for positioning bolts/nuts consistently during measurement.",
      "Position IR sensing components close enough to the thread profile without interfering with the incoming component.",
      "Account for fabrication and assembly tolerances that could affect measurement accuracy.",
      "Develop a mechanical holder that can accommodate different nut diameters.",
    ],
    role: {
      title: "Mechanical Concept & Test-Rig Design",
      points: [
        "Developed the mechanical bolt/nut holder and sensing concepts.",
        "Designed multiple spring-loaded gripping mechanisms.",
        "Investigated mirror and mirrorless sensing architectures.",
        "Designed the sensor mounting geometry.",
        "Performed tolerance/deviation analysis of the sensing arrangement.",
        "Developed the mechanical nut holder and diameter indicators.",
        "Designed concepts for a mechanical caliper integrated into the enclosure.",
      ],
    },
    results: [
      "Multiple sensing concepts evaluated — compared mirror-based and direct line-of-sight approaches.",
      "Tolerance-driven concept rejection — identified that ±0.2 mm X/Y positioning and ±1–2° mirror rotation could introduce significant measurement deviation.",
      "Mirrorless alternative developed — investigated a 60° direct sensing arrangement to improve consistency.",
      "Adaptive mechanical holder — developed gripping and diameter-indication features for different nut sizes.",
      "Designed the system around mechanical positioning accuracy rather than relying purely on software correction.",
    ],
    approach: {
      flow: "Concept → Identify Error Sources → Simulate Tolerance → Reject/Refine → Develop Alternative → Validate",
      body: "This project demonstrates a particularly strong engineering workflow: using tolerance analysis to identify weaknesses in a concept before committing to fabrication.",
    },
    gallery: [
      { file: "housing-render.jpg", alt: "Thread finder housing, exterior render", caption: "Housing render" },
      { file: "internal-cross-section.jpg", alt: "Internal cross-section showing the sensing mechanism", caption: "Internal cross-section" },
      { file: "sensing-diagram.jpg", alt: "Top-view diagram of the sensing arrangement", caption: "Sensing diagram" },
      { file: "section-view.jpg", alt: "Section-view render of the assembled housing", caption: "Section view" },
      {
        file: "positioning-deviation-simulation.jpg",
        alt: "Positioning-deviation simulation chart",
        caption: "Positioning deviation simulation \u2014 X/Y tolerance \u00b10.2 mm, mirror rotation \u00b11\u00b0 to \u00b12\u00b0",
      },
    ],
  },

  // ────────────────────────────────────────────────────────────────
  // SECONDARY
  // ────────────────────────────────────────────────────────────────
  {
    slug: "autonomous-steering",
    title: "Autonomous Steering System",
    type: "Autonomous Electric Vehicle — Shell Eco-marathon Poland 2026",
    categories: ["prototype-vehicle", "simulation-analysis"],
    featured: false,
    sourceVerified: true,
    summary:
      "An autonomous electric steering system for the Shell Eco-marathon Autonomous Driving Competition, converting a conventional rack-and-pinion steering system into a motor-actuated, computer-controlled mechanism — sized to hit the required steering force and response inside tight vehicle-packaging constraints.",
    tags: [
      "Mechanical Design",
      "Autonomous Systems",
      "Steering Systems",
      "Mechatronics",
      "Kinematics",
      "Actuator Design",
      "Torque Analysis",
      "CAD",
      "Systems Integration",
      "Prototyping",
    ],
    hero: { file: "hero.jpg", alt: "Autonomous steering actuator mounted to the rack-and-pinion assembly", caption: "Steering actuator" },
    problem: [
      "Add autonomous steering without redesigning the entire steering system.",
      "Convert the existing manual rack-and-pinion steering into an electronically actuated system suitable for autonomous driving.",
      "Achieve the required rack force, rack speed, and steering angle within the vehicle's limited packaging space.",
      "Develop an actuator capable of overcoming static tire friction while maintaining sufficient torque margin for dynamic operation.",
      "Integrate the actuator with the existing steering mechanism while minimizing additional mechanical complexity and backlash.",
      "Complete the design under a highly compressed vehicle-development timeline.",
    ],
    role: {
      title: "Mechanical Designer",
      points: [
        "Designed the mechanical architecture of the autonomous steering actuator and its interface with the existing rack-and-pinion system.",
        "Developed the actuator mounting and mechanical transmission between the motor and steering rack.",
        "Performed analytical sizing of the actuator based on rack-force and steering requirements.",
        "Conducted direct static-torque measurements on the vehicle to establish the actual actuation requirement.",
        "Selected and integrated a NEMA 34 stepper motor with a 2:1 reduction gearbox.",
        "Optimized the mechanism for compact packaging, rapid fabrication, and reliable integration.",
        "Validated the steering geometry and actuator requirements against the vehicle's operating targets.",
      ],
    },
    results: [
      "12.8 N·m design torque capability — actuator architecture developed around a measured 6.38 N·m minimum static torque requirement, with a recommended 12.8 N·m design target providing additional operating margin.",
      "1-second lock-to-lock target — designed around a 45 mm/s rack-speed requirement to enable rapid steering transitions for autonomous manoeuvres.",
      "1,000 N rack-force design requirement — sized the actuation system around the adopted worst-case standstill loading condition.",
      "NEMA 34 + 2:1 reduction — implemented a high-torque stepper-driven architecture directly coupled to the rack-and-pinion mechanism, avoiding unnecessary intermediate linkages.",
      "Compact integration — designed the actuator and gearbox around the existing vehicle steering architecture rather than replacing the complete steering system.",
      "18° maximum steering angle — maintained the mechanically limited steering range while working within the existing rack geometry.",
      "6.24 m turning radius — the underlying rack-and-pinion geometry achieved a turning radius compliant with the vehicle's maneuverability requirement.",
    ],
    approach: {
      flow: "Requirement → Measure → Calculate → Select → Package → Fabricate → Integrate → Validate",
      body: "Rather than designing the actuator independently, the system was developed around the existing rack-and-pinion geometry and measured vehicle requirements. Analytical rack-force estimation was combined with direct static-torque measurement to select the actuator, followed by mechanical packaging and integration around the existing steering system.",
    },
    parameters: {
      heading: "Design Parameters",
      rows: [
        { label: "Wheelbase", symbol: "L", value: "1803 mm" },
        { label: "Front track (selected)", symbol: "T", value: "700 mm" },
        { label: "Steering arm length", symbol: "r", value: "93 mm" },
        { label: "Tie-rod length", symbol: "lₜ", value: "170 mm" },
        { label: "Rack inner pivot spacing", symbol: "S", value: "335 mm" },
        { label: "Rack total stroke", symbol: "Xₜ", value: "84.5 mm" },
        { label: "Rack travel per side", symbol: "δ", value: "42.25 mm" },
        { label: "Design inside steering angle", symbol: "δᵢₙ", value: "18°" },
      ],
    },
    sections: [
      {
        heading: "Actuator Sizing",
        body: [
          "The autonomous steering actuator was sized from a direct static-torque measurement on the vehicle: 65 kg·cm (6.38 N·m) minimum torque to overcome static friction, with a recommended design torque of 130 kg·cm (12.8 N·m) for adequate margin under dynamic conditions.",
          "A NEMA 34 stepper motor drives the rack through a 2:1 gear reduction, coupling the motor output to the pinion and rack assembly.",
          "The steering design used an 84.5 mm available rack stroke, with 42.25 mm of travel per side, while the required travel for the target 18° steering angle was 60.4 mm total — providing sufficient mechanical range, with steering stops used to prevent excessive motion.",
        ],
      },
    ],
    gallery: [
      { file: "gearbox-detail.jpg", alt: "Steering gearbox and pinion detail", caption: "Gearbox detail" },
      { file: "actuator-mount.jpg", alt: "NEMA 34 stepper actuator mount", caption: "Actuator mount" },
    ],
  },
  {
    slug: "magnetic-charger",
    title: "Magnetic Contact Charger",
    type: "DFMA & Manufacturing-Oriented Design",
    categories: ["products", "fabrication"],
    featured: false,
    sourceVerified: true,
    summary:
      "A compact magnetic electrical connector that integrates spring-loaded pogo pins, magnets, PCB assemblies, and a molded enclosure, developed with a focus on mechanical alignment, assembly, and scalable manufacturing.",
    tags: [
      "DFMA",
      "Mechanical Design",
      "Injection Molding",
      "Overmolding",
      "Assembly Design",
      "Manufacturing",
      "CAD",
      "Product Development",
    ],
    hero: { file: "hero.jpg", alt: "Magnetic contact charger, rendered housing with pogo-pin contacts", caption: "Charger housing" },
    problem: [
      "Develop a compact magnetic electrical connector that can be assembled reliably and scaled toward manufacturing.",
      "Combine electrical contacts, magnets, PCB assemblies, and mechanical housings in a very small package.",
      "Maintain accurate alignment between mating components.",
      "Protect delicate pogo-pin and PCB assemblies.",
      "Develop the product around a scalable manufacturing process rather than manual assembly alone.",
    ],
    role: {
      title: "Mechanical Designer / DFMA",
      points: [
        "Designed the mechanical assembly and enclosure.",
        "Developed the PCB frame and component alignment features.",
        "Integrated pogo pins and magnets into the mechanical architecture.",
        "Developed the enclosure around the intended overmolding process.",
        "Considered manufacturing and assembly constraints throughout the design.",
        "Worked on component positioning and mechanical interfaces.",
      ],
    },
    results: [
      "DFMA-driven assembly architecture — designed the mechanical structure around repeatable component positioning.",
      "Overmolding-ready design — developed the PCB frame to maintain alignment during the molding process.",
      "Integrated magnetic connection — combined N52 magnets and spring-loaded pogo pins into a compact interface.",
      "Designed around scalable manufacturing rather than prototype-only assembly.",
    ],
    approach: {
      flow: "Component Selection → Assembly Architecture → Alignment → DFMA → Tooling/Process → Manufacturing",
      body: "The enclosure and internal layout were developed around the intended overmolding and assembly process from the outset, rather than designed first and adapted for manufacturing afterward.",
    },
    gallery: [
      { file: "render-1.jpg", alt: "Magnetic contact charger, angled render", caption: "Angled render" },
      { file: "render-2.jpg", alt: "Magnetic contact charger, front render", caption: "Front render" },
      { file: "render-3.jpg", alt: "Magnetic contact charger, side render", caption: "Side render" },
      { file: "breadboard-prototype.jpg", alt: "Early breadboard prototype with pogo-pin wiring", caption: "Breadboard prototype" },
    ],
  },
  {
    slug: "crop-washer",
    title: "Rotary Drum Crop Washer",
    type: "Machine Design & Fabrication",
    categories: ["fabrication", "products"],
    featured: false,
    sourceVerified: true,
    summary:
      "A fabrication-oriented machine-design project focused on translating a conceptual rotary drum crop-washing system into a physical, functional, and as-built machine.",
    tags: [
      "Machine Design",
      "DFMA",
      "Fabrication",
      "CAD",
      "Agricultural Machinery",
      "Mechanical Systems",
      "Design for Fabrication",
    ],
    hero: { file: "hero.jpg", alt: "Rotary drum crop washer, CAD render", caption: "Crop washer render" },
    problem: [
      "Translate a conceptual crop-washing system into a fabricable and functional machine.",
      "Develop a machine capable of handling and washing agricultural produce through a rotating drum.",
      "Design the structure around available fabrication processes and materials.",
      "Ensure the drum, shaft, bearings, drive, and supporting structure can work as an integrated system.",
      "Convert the conceptual design into an as-built machine.",
    ],
    role: {
      title: "Mechanical Designer / Fabrication-Oriented Engineer",
      points: [
        "Developed the mechanical architecture for fabrication.",
        "Designed the drum, frame, shaft, and supporting components.",
        "Designed around available fabrication methods and component availability.",
        "Prepared the system for physical fabrication and assembly.",
        "Documented the as-built configuration and design changes.",
      ],
    },
    results: [
      "Design-for-fabrication approach — developed the machine around realistic fabrication capabilities rather than an idealized CAD-only design.",
      "As-built mechanical design — translated the design into a physical machine while accounting for actual fabrication conditions.",
      "Integrated drum, shaft, bearing, drive, and structural systems into a functional machine.",
    ],
    approach: {
      flow: "Concept → Fabrication Constraints → CAD → Build → Observe → Modify → As-Built",
      body: "The design moved deliberately from an idealized concept toward an as-built machine — accounting for available fabrication processes and materials at every stage, and documenting changes made once the drum, shaft, and drive were actually built and observed running together.",
    },
    gallery: [
      { file: "cad-render-1.jpg", alt: "Rotary drum crop washer, CAD render, front view", caption: "CAD render, front" },
      { file: "cad-render-2.jpg", alt: "Rotary drum crop washer, transparent-frame CAD render", caption: "Transparent-frame render" },
      { file: "cad-render-3.jpg", alt: "Rotary drum crop washer, CAD render, side profile", caption: "Side profile render" },
      { file: "as-built.jpg", alt: "As-built rotary drum crop washer, painted green", caption: "As-built machine" },
      { file: "drum-mesh-detail.jpg", alt: "Rotary drum mesh and frame detail", caption: "Drum mesh detail" },
      { file: "hopper-detail.jpg", alt: "Feed hopper detail, green housing", caption: "Hopper detail" },
    ],
  },
  {
    slug: "wells-turbine",
    title: "Wave Generator with Wells Turbine",
    type: "Concept Design · Airfoil & Fluid Machinery",
    categories: ["simulation-analysis", "products"],
    featured: false,
    sourceVerified: true,
    summary:
      "A renewable-energy concept design project developing a six-bladed Wells turbine for wave-energy conversion, including the generation of a NACA 0021 airfoil profile using the plotting method and its integration into the turbine blade geometry and mechanical assembly.",
    tags: [
      "Concept Design",
      "Airfoil Design",
      "NACA 0021",
      "Wells Turbine",
      "Mechanical Design",
      "Fluid Machinery",
      "Renewable Energy",
      "CAD",
      "Design for Fabrication",
    ],
    hero: { file: "hero.jpg", alt: "Wells turbine wave-energy test flume, CAD render", caption: "Test flume render" },
    problem: [
      "Develop a practical Wells turbine concept capable of converting oscillating airflow from wave motion into rotational energy.",
      "Develop a turbine geometry suitable for an oscillating airflow environment.",
      "Generate and construct an appropriate NACA airfoil profile for the turbine blade.",
      "Translate the 2D airfoil profile into a manufacturable 3D blade geometry.",
      "Develop the turbine rotor, hub, and blade arrangement around the selected geometry.",
      "Maintain appropriate geometric proportions for the turbine while considering fabrication and system integration.",
    ],
    role: {
      title: "Mechanical Designer / Concept Development",
      points: [
        "Designed the Wells turbine blade and rotor architecture.",
        "Generated the NACA 0021 airfoil profile using the plotting method.",
        "Developed the 3D turbine blade geometry from the plotted airfoil profile.",
        "Designed the six-blade rotor and 90 mm hub around the turbine's overall 150 mm diameter.",
        "Developed the blade dimensions and geometry, including 82.5 mm blade length and 40 mm chord.",
        "Designed the mechanical arrangement for integration with the wave-energy generator.",
        "Considered geometric proportions, shaft interface, packaging, and fabrication requirements during the design process.",
      ],
    },
    results: [
      "NACA 0021 airfoil developed — generated the airfoil geometry using the plotting method as the basis for the Wells turbine blade.",
      "Six-bladed turbine architecture — developed a compact rotor with a 150 mm overall diameter and 90 mm hub diameter.",
      "Defined blade geometry — established an 82.5 mm hub-to-tip blade length with a 40 mm chord.",
      "Geometrically validated concept — calculated a solidity of 0.64, an aspect ratio of 1.65, and a hub ratio of 0.34 based on the developed turbine geometry.",
      "~764 RPM estimated operating speed — calculated an expected rotational speed at 10 m/s airflow based on the turbine dimensions and assumed tip-speed relationship.",
      "Developed a complete CAD concept ready for fabrication and further experimental development.",
    ],
    approach: {
      flow: "Airfoil Plotting → Blade Geometry → Dimensioning → Rotor Layout → Proportion Check → CAD Integration",
      body: "The design began with the mathematical construction of the NACA 0021 airfoil, which was then translated into the turbine blade geometry and integrated into the six-bladed rotor. Key geometric parameters such as solidity, aspect ratio, hub ratio, and expected rotational speed were calculated to establish a coherent turbine configuration before fabrication.",
    },
    parameters: {
      heading: "Turbine Geometry",
      rows: [
        { label: "Overall rotor diameter", symbol: "D", value: "150 mm" },
        { label: "Hub diameter", symbol: "Dₕ", value: "90 mm" },
        { label: "Blade length (hub-to-tip)", symbol: "l", value: "82.5 mm" },
        { label: "Blade chord", symbol: "c", value: "40 mm" },
        { label: "Solidity", symbol: "σ", value: "0.64" },
        { label: "Aspect ratio", symbol: "AR", value: "1.65" },
        { label: "Hub ratio", symbol: "ν", value: "0.34" },
        { label: "Est. operating speed (at 10 m/s airflow)", symbol: "N", value: "~764 RPM" },
      ],
    },
    gallery: [
      { file: "test-flume.jpg", alt: "Wave-energy test flume, full CAD render", caption: "Full test flume" },
      { file: "rotor-top-view.jpg", alt: "Six-bladed rotor, top view", caption: "Rotor top view" },
      { file: "rotor-hub-assembly.jpg", alt: "Rotor and hub assembly render", caption: "Rotor and hub assembly" },
      { file: "flume-setup.jpg", alt: "Glass wave-flume test setup render", caption: "Flume setup" },
      {
        file: "naca-0021-profile.jpg",
        alt: "NACA 0021 airfoil profile plot with dimensions",
        caption: "NACA 0021 airfoil, plotted profile and blade dimensions",
      },
    ],
  },
  {
    slug: "boat-docking-claw",
    title: "Boat Docking Claw Arm",
    type: "Simulation & Pivot Redesign",
    categories: ["simulation-analysis"],
    featured: false,
    sourceVerified: true,
    summary:
      "A simulation-only look at a boat-docking claw arm's pivot \u2014 using FEA under a 200 N load to confirm why the original hook flexed in use, and checking a stiffer, 3D-print-optimized pivot redesign against it.",
    tags: ["FEA", "Simulation", "Pivot Design", "3D Printing", "Mechanical Design"],
    hero: {
      file: "hero.jpg",
      alt: "FEA stress comparison of the original and redesigned claw-arm pivot",
      caption: "FEA stress comparison",
    },
    role: {
      title: "Mechanical Designer / Simulation",
      points: [
        "Simulated the claw arm under a 200 N load, representative of manual boat-docking use on small recreational boats.",
        "Identified visible flexure and constant deformation at the pivot walls as the cause of the claw's flimsy feel.",
        "Redesigned the pivot with a thicker wall and dowel-pin reinforcement, optimized for 3D printing.",
      ],
    },
    sections: [
      {
        heading: "Previous Design",
        body: [
          "The previous pivot design showed noticeable flexure and constant deformation at its walls \u2014 one of the reasons the claw felt flimsy in use.",
        ],
      },
      {
        heading: "Load Case",
        body: ["A 200 N load was used to simulate a manual boat-docking hook for small recreational boats."],
      },
      {
        heading: "Redesign",
        body: [
          "The redesigned pivot adds a thicker wall with dowel-pin reinforcement, letting the claw hold the dock at lower stress under the same load.",
        ],
      },
    ],
    results: [
      "Previous design flexed by up to 102 mm once the claw caught a dock.",
      "New design flexes by only 45 mm \u2014 a 126.7% increase in stiffness.",
      "FEA identified the pivot wall as the primary source of flex in the original claw design.",
      "The redesigned pivot \u2014 thicker wall plus dowel-pin reinforcement \u2014 holds the same 200 N load at lower stress than the original.",
    ],
    gallery: [
      {
        file: "fea-comparison.jpg",
        alt: "FEA stress comparison: original vs. redesigned pivot",
        caption: "Stress \u2014 previous design (top) vs. redesigned pivot with dowel-pin reinforcement (bottom), both under 200 N",
      },
      {
        file: "deflection-comparison.jpg",
        alt: "Deflection comparison: 102 mm previous design vs. 45 mm redesigned pivot",
        caption: "Deflection \u2014 102 mm previous design (left) vs. 45 mm redesigned pivot (right)",
      },
    ],
  },
];

export const FEATURED_PROJECTS = PROJECTS.filter((p) => p.featured);
export const SECONDARY_PROJECTS = PROJECTS.filter((p) => !p.featured);

export function getProject(slug: string): Project | undefined {
  return PROJECTS.find((p) => p.slug === slug);
}
